// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var WebsocketClient$ReactHooksTemplate = require("./WebsocketClient.bs.js");

var ws = WebsocketClient$ReactHooksTemplate.Websocket[/* make */0](/* array */["protocolOne"], "ws://localhost:3000/");

function App(Props) {
  ws.onopen = (function (param) {
      ws.send("SENT!");
      return /* () */0;
    });
  return React.createElement("h1", undefined, "sup");
}

var make = App;

exports.ws = ws;
exports.make = make;
/* ws Not a pure module */
