// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';


var OpenEvent = /* module */[];

function make($staropt$star, url) {
  var protocols = $staropt$star !== undefined ? $staropt$star : /* array */[];
  return new WebSocket(url, protocols);
}

var Websocket = /* module */[/* make */make];

exports.OpenEvent = OpenEvent;
exports.Websocket = Websocket;
/* No side effect */
